name = "Truelymon Resurgence"
author = "Truely and Freddie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12d27d26284cba2faf0e0949a6f165633969315c5452d51faf5be873bf6c043a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
acceptable-game-versions = []
