name = "Truelymon Resurgence"
author = "Truely and Freddie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec076d10c74f4f4593448b15eefc15ddb24c9e70675aae23616753c5e971e059"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
acceptable-game-versions = []
