name = "Truelymon Resurgence"
author = "Truely and Freddie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50a2e4f153d0d85d8c71292814c1d871238be7b9117e163818fd2cfe813ab285"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
